platform :ios, '13.0'

target 'ZcashLightClientSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "KRProgressHUD"
  # Pods for ZcashLightClientSample
  pod 'ZcashLightClientKit', :path => '../../', :testspecs => ['Tests', 'DerivationToolTests']
  pod 'gRPC-Swift', '= 1.0.0'
  pod 'PaginatedTableView'
  pod 'NotificationBubbles'
  pod 'MnemonicSwift', '~> 2.0.0'
  pod 'gRPC-Swift-Plugins', '= 1.0.0'
  target 'ZcashLightClientSampleTests' do
    use_frameworks!
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZcashLightClientSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ZcashLightClientSample-Mainnet' do
  inherit! :search_paths
  use_frameworks!
  pod 'MnemonicSwift', '~> 2.0.0'
  pod "KRProgressHUD"
  pod 'PaginatedTableView'
  pod 'NotificationBubbles'
  pod 'ZcashLightClientKit', :path => '../../'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
 #     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      if target.name == 'ZcashLightClientKit-Unit-Tests'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
      end
     
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
