platform :ios, '12.0'

target 'ZcashLightClientSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZcashLightClientSample
  pod 'ZcashLightClientKit', :path => '../../', :testspecs => ['Tests']
  target 'ZcashLightClientSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZcashLightClientSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
