platform :ios, '12.0'

target 'ZcashLightClientSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "KRProgressHUD"
  # Pods for ZcashLightClientSample
  pod 'ZcashLightClientKit', :path => '../../', :testspecs => ['Tests']
  pod 'PaginatedTableView'
  pod 'NotificationBubbles'
  target 'ZcashLightClientSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZcashLightClientSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.include? '-Unit-Tests'
      Xcodeproj::XCScheme.share_scheme(installer.pods_project.path, target.name)
    end
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
